### PR TITLE
Dart 3 compatible

### PR DESCRIPTION
**Pull request by davidmartos96**
Hello! 
Thanks for the small useful package. This PR makes it compatible with the just released Dart 3.
Right now the tool cannot be installed when using Dart 3

I changed the lint package to use the official one from the Dart team https://pub.dev/packages/lints

### CODE REVIEW

**Review by lukas-h — APPROVED** [review]

**Comment by lukas-h** [comment]
hi @davidmartos96 Thank you very much for your help!
Merged it. Will release a new version to pub in the coming days

**Comment by davidmartos96** [comment]
@lukas-h Great, thank you!

**Comment by davidmartos96** [comment]
@lukas-h Hello! Just wanted to let you know that the update hasn't been pushed yet to pub.dev :sweat_smile:

**Comment by lukas-h** [comment]
@davidmartos96 it's live now: https://pub.dev/packages/dart_clean/versions/0.2.0

Thanks for reminding!

**Pull request merged**
